dist: bionic
language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10-dev"
    - python: "3.11-dev"
install:
  - pip install tox-travis
  - curl -sSL https://pdm.fming.dev/dev/install-pdm.py | python3 -
script: tox
