language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
  allow_failures:
    - python: "3.8-dev"
install: pip install tox-travis poetry
script: tox
